services:
  app:
    image: wawarehouse-accounting
    build:
      context: .
    ports:
      - '8080:8080'
    depends_on:
      - db
    restart: on-failure
    container_name: app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/warehouse_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

  db:
    image: postgres:17
    restart: on-failure
    container_name: db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
